openapi: 3.0.4

info:
  title: Membrane MockServer API
  version: 1.0.0

paths:
  /reset:
    post:
      operationId: reset-server
      description: Reset all configuration
      responses:
        204:
          description: Mock Server Reset

  /operation/{operationId}:
    parameters:
      - name: operationId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OperationId"
    post:
      operationId: add-operation
      responses:
        201:
          description: Operation Created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - default
              properties:
                default:
                  type: object
                  required:
                    - response
                  properties:
                    response:
                      $ref: "#/components/schemas/Response"
    delete:
      operationId: delete-operation
      responses:
        204:
          description: Operation Deleted

  /operation/{operationId}/matcher:
    parameters:
      - name: operationId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OperationId"
    post:
      operationId: add-matcher
      responses:
        201:
          description: Matcher Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  operationId:
                    $ref: "#/components/schemas/OperationId"
                  matcher:
                    $ref:  "#/components/schemas/Matcher"
                  response:
                    $ref: "#/components/schemas/Response"


      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                matcher:
                  $ref:  "#/components/schemas/Matcher"
                response:
                  $ref: "#/components/schemas/Response"
    delete:
      operationId: delete-matcher
      responses:
        204:
          description: Matcher Deleted

components:
  schemas:
    OperationId:
      type: string
      description: This MUST be an operationId from your OpenAPI Specification
    Response:
      anyOf:
        - type: integer
        - type: object
          properties:
            code:
              type: integer
            headers:
              type: object
              additionalProperties:
                anyOf:
                  - type: string
                  - type: array
                    items:
                      type: string
            body:
              anyOf:
                - type: string
                - type: array
    Matcher:
      type: object
      required:
        - type
        - args
      properties:
        type:
          type: string
          description: An alias as defined by your config.
          example: equals
        args:
          type: object
          description: named arguments as required by the matcher specified by type.
