openapi: 3.0.4

info:
  title: Membrane MockServer API
  version: 1.0.0

paths:
  /reset:
    post:
      operationId: reset
      description: Reset all configuration
      responses:
        204:
          description: Mock Server Reset
  /operation/{operationId}:
    parameters:
      - name: operationId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OperationId"
    post:
      operationId: add-operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - default
              properties:
                default:
                  type: object
                  required:
                    - response
                  properties:
                    response:
                      $ref: "#/components/schemas/Response"
      responses:
        201:
          description: Operation Created
    delete:
      operationId: delete-operation
      responses:
        204:
          description: Operation Deleted
  /operation/{operationId}/matcher:
    parameters:
      - name: operationId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OperationId"

    post:
      operationId: add-matcher
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                matcher:
                  $ref:  "#/components/schemas/Matcher"
                response:
                  $ref: "#/components/schemas/Response"
      responses:
        201:
          description: Matcher Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  operationId:
                    $ref: "#/components/schemas/OperationId"
                  matcher:
                    $ref:  "#/components/schemas/Matcher"
                  response:
                    $ref: "#/components/schemas/Response"
  /operation/{operationId}/matcher/{matcherId}:
    parameters:
      - name: operationId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OperationId"
      - name: matcherId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    delete:
      operationId: delete-matcher
      responses:
        204:
          description: Matcher Deleted
components:
  schemas:
    OperationId:
      type: string
      description: This MUST be an operationId from your OpenAPI Specification
    Response:
      type: object
      required:
        - code
      properties:
        code:
          type: integer
        headers:
          type: object
          additionalProperties:
            type: string
        body:
          type: string
    Matcher:
      type: object
      required:
        - type
        - args
      properties:
        type:
          type: string
          description: An alias as defined by your config.
          example: equals
        args:
          type: object
          description: named arguments as required by the matcher specified by type.
